on: push

jobs:
  test-suite:
    runs-on: ubuntu-20.04
    name: Docker build test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64

